In [1]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
import time
import os
import re
from datetime import datetime
from urllib3.util.retry import Retry
from requests.adapters import HTTPAdapter

# =========================
# SETTINGS
# =========================

input_file = "goobjoog_ciyaaraha_links.xlsx"

# Use a NEW sample output file first
output_file = "goobjoog_ciyaaraha_scraped_articles_SAMPLE10.xlsx"

TEST_LIMIT = 10          # First test only 10 links
SAVE_EVERY = 2           # Save checkpoint after every 2 articles
MIN_BODY_WORDS = 50      # Used only for warning/checking
REQUEST_DELAY = 2.5

CATEGORY = "ciyaaro"
SOURCE = "Goobjoog"

FORCE_RESCRAPE_EMPTY = True
# If output_file exists, this will re-scrape rows whose body is empty/too short


# =========================
# SESSION
# =========================

def get_robust_session():
    session = requests.Session()

    retry = Retry(
        total=5,
        connect=5,
        read=5,
        backoff_factor=1.5,
        status_forcelist=[429, 500, 502, 503, 504],
        allowed_methods=["GET"],
        raise_on_status=False
    )

    adapter = HTTPAdapter(max_retries=retry)
    session.mount("http://", adapter)
    session.mount("https://", adapter)

    session.headers.update({
        "User-Agent": (
            "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
            "AppleWebKit/537.36 (KHTML, like Gecko) "
            "Chrome/124.0.0.0 Safari/537.36"
        ),
        "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8",
        "Accept-Language": "so,en-US;q=0.9,en;q=0.8",
        "Connection": "keep-alive",
    })

    return session


# =========================
# TEXT CLEANING HELPERS
# =========================

def normalize_text(text):
    if pd.isna(text):
        return ""

    text = str(text)
    text = text.replace("\xa0", " ")
    text = text.replace("\ufeff", "")
    text = text.replace("\r\n", "\n").replace("\r", "\n")
    text = text.replace("“", '"').replace("”", '"')
    text = text.replace("‘", "'").replace("’", "'")
    text = text.replace("–", "-").replace("—", "-")
    text = re.sub(r"[ \t]+", " ", text)
    text = re.sub(r"\n{3,}", "\n\n", text)

    return text.strip()


STOP_PATTERNS = [
    r"^W/D\s*[-–]",
    r"^W/Q\s*[-–]",
    r"^Isla Qaybtaan$",
    r"^Qaybaha$",
    r"^Mawduucyada$",
    r"^Noocyada Qormooyinka$",
    r"^Goobjoog$",
    r"^La Xiriir$",
    r"^©\s*\d{4}",
    r"^Xuquuqda faafintu",
]

REMOVE_PATTERNS = [
    r"^Goobjoog News$",
    r"^Googjoog News$",
    r"^Dhageyso$",
    r"^Halkaan hoose ka dhageyso",
    r"^Halkaan ka Akhriso",
    r"^Rukumo",
    r"^Share",
    r"^Facebook$",
    r"^Twitter$",
    r"^WhatsApp$",
    r"^Telegram$",
]


def should_stop_line(line):
    return any(re.search(pattern, line, flags=re.IGNORECASE) for pattern in STOP_PATTERNS)


def should_remove_line(line):
    return any(re.search(pattern, line, flags=re.IGNORECASE) for pattern in REMOVE_PATTERNS)


def clean_lines(lines):
    cleaned = []

    for raw_line in lines:
        line = normalize_text(raw_line)

        if not line:
            continue

        if should_stop_line(line):
            break

        if should_remove_line(line):
            continue

        # remove very tiny non-article fragments
        if len(line.split()) < 3:
            continue

        cleaned.append(line)

    # Remove repeated adjacent lines
    deduped = []
    for line in cleaned:
        if not deduped or deduped[-1] != line:
            deduped.append(line)

    return "\n".join(deduped).strip()


# =========================
# EXTRACTION HELPERS
# =========================

def extract_headline(soup):
    selectors = [
        "h1.entry-title",
        "h1.post-title",
        "h1"
    ]

    for selector in selectors:
        tag = soup.select_one(selector)
        if tag:
            headline = normalize_text(tag.get_text(" ", strip=True))
            if headline:
                return headline

    return ""


def extract_paragraphs_from_container(container):
    # Remove unwanted HTML blocks
    for tag in container.select("script, style, aside, nav, footer, header, form, iframe, ins"):
        tag.decompose()

    paragraphs = container.find_all("p")

    if paragraphs:
        return [p.get_text(" ", strip=True) for p in paragraphs]

    # fallback if the container has text but not paragraph tags
    return container.get_text("\n", strip=True).splitlines()


def extract_body(soup):
    # First try likely article containers
    container_selectors = [
        "div.entry-content",
        "article div.entry-content",
        "div.post-content",
        "div.article-content",
        "div.td-post-content",
        "article",
        "main",
    ]

    best_body = ""

    for selector in container_selectors:
        container = soup.select_one(selector)

        if not container:
            continue

        lines = extract_paragraphs_from_container(container)
        body = clean_lines(lines)

        if len(body.split()) > len(best_body.split()):
            best_body = body

        # good enough, return early
        if len(body.split()) >= MIN_BODY_WORDS:
            return body

    # Final fallback: collect all page paragraphs
    all_paragraphs = [p.get_text(" ", strip=True) for p in soup.find_all("p")]
    fallback_body = clean_lines(all_paragraphs)

    if len(fallback_body.split()) > len(best_body.split()):
        best_body = fallback_body

    return best_body


def scrape_goobjoog_article(url, session):
    try:
        response = session.get(url, timeout=25)

        status_code = response.status_code

        if status_code != 200:
            return {
                "headline": "",
                "body": "",
                "status": f"failed_status_{status_code}",
                "error": f"HTTP status {status_code}"
            }

        soup = BeautifulSoup(response.content, "html.parser")

        headline = extract_headline(soup)
        body = extract_body(soup)

        body_word_count = len(body.split())

        if not headline and not body:
            status = "failed_no_headline_no_body"
        elif not body:
            status = "warning_no_body"
        elif body_word_count < MIN_BODY_WORDS:
            status = "warning_short_body"
        else:
            status = "ok"

        return {
            "headline": headline,
            "body": body,
            "status": status,
            "error": ""
        }

    except Exception as e:
        return {
            "headline": "",
            "body": "",
            "status": "exception",
            "error": str(e)
        }


# =========================
# LOAD LINKS
# =========================

if not os.path.exists(input_file):
    raise FileNotFoundError(f"{input_file} not found. Make sure it is in the same folder as this notebook.")

df_links = pd.read_excel(input_file)

print("Columns in links file:")
print(df_links.columns.tolist())

# Accept URL or url column
if "URL" in df_links.columns:
    url_col = "URL"
elif "url" in df_links.columns:
    url_col = "url"
else:
    raise ValueError("No URL column found. Your file must contain 'URL' or 'url'.")

urls_to_scrape = (
    df_links[url_col]
    .dropna()
    .astype(str)
    .str.strip()
    .drop_duplicates()
    .tolist()
)

if TEST_LIMIT is not None:
    urls_to_scrape = urls_to_scrape[:TEST_LIMIT]

print(f"\nTotal URLs selected for this run: {len(urls_to_scrape)}")


# =========================
# CHECKPOINT / RESUME
# =========================

scraped_data = []
processed_urls = set()

if os.path.exists(output_file):
    df_existing = pd.read_excel(output_file)

    if FORCE_RESCRAPE_EMPTY and not df_existing.empty:
        df_existing["body"] = df_existing["body"].fillna("").astype(str)
        df_existing["body_word_count"] = df_existing["body"].str.split().str.len()

        df_good_existing = df_existing[df_existing["body_word_count"] >= MIN_BODY_WORDS].copy()

        removed_count = len(df_existing) - len(df_good_existing)

        scraped_data = df_good_existing.drop(columns=["body_word_count"], errors="ignore").to_dict("records")
        processed_urls = set(df_good_existing["url"].astype(str).tolist())

        print(f"\nResuming from checkpoint: {len(processed_urls)} good rows kept.")
        print(f"Rows with empty/short body will be re-scraped: {removed_count}")
    else:
        scraped_data = df_existing.to_dict("records")
        processed_urls = set(df_existing["url"].astype(str).tolist())
        print(f"\nResuming from checkpoint: {len(processed_urls)} rows already scraped.")


# =========================
# MAIN SCRAPE LOOP
# =========================

session = get_robust_session()

print("\nStarting Goobjoog Ciyaaro sample scrape...\n")

for i, url in enumerate(urls_to_scrape, start=1):
    if url in processed_urls:
        print(f"[{i}/{len(urls_to_scrape)}] Skipping already processed: {url}")
        continue

    print("=" * 90)
    print(f"[{i}/{len(urls_to_scrape)}] Scraping: {url}")

    result = scrape_goobjoog_article(url, session)

    headline = result["headline"]
    body = result["body"]
    status = result["status"]
    error = result["error"]

    body_word_count = len(body.split())

    row = {
        "url": url,
        "headline": headline,
        "body": body,
        "category": CATEGORY,
        "source": SOURCE,
        "status": status,
        "body_word_count": body_word_count,
        "scraped_at": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "error": error
    }

    scraped_data.append(row)
    processed_urls.add(url)

    print(f"Status: {status}")
    print(f"Headline: {headline[:120] if headline else 'NO HEADLINE'}")
    print(f"Body words: {body_word_count}")
    print(f"Body preview: {body[:250].replace(chr(10), ' ') if body else 'NO BODY'}")

    if len(scraped_data) % SAVE_EVERY == 0:
        pd.DataFrame(scraped_data).to_excel(output_file, index=False)
        print(f"Checkpoint saved: {len(scraped_data)} rows -> {output_file}")

    time.sleep(REQUEST_DELAY)

# Final save
df_out = pd.DataFrame(scraped_data)
df_out.to_excel(output_file, index=False)

print("\n" + "=" * 90)
print(f"Scraping complete. Saved {len(df_out)} rows to {output_file}")
print("\nStatus counts:")
print(df_out["status"].value_counts(dropna=False))

print("\nBody word count summary:")
print(df_out["body_word_count"].describe())

df_out[["url", "headline", "body_word_count", "status", "body"]].head(10)

Columns in links file:
['URL']

Total URLs selected for this run: 10

Starting Goobjoog Ciyaaro sample scrape...

==========================================================================================
[1/10] Scraping: https://goobjoog.com/2020/12/31/yaa-guulaysan-doono-gobolka-banaadir-iyo-galmudug-tartanka-maamul-goboleedyada-2020/
Status: ok
Headline: Yaa Guulaysan Doono Gobolka Banaadir Iyo Galmudug Tartanka Maamul Goboleedyada 2020
Body words: 221
Body preview: Kooxaha Kubbadda Cagta Gobolka Banaadir iyo Galmudug ayaa markii ugu horeesay wada dheeli doono heerka ugu danbeeya tartanka kubbadda cagta Maamul Goboleedyada iyo Gobolka Banaadir. Labada koox oo ka soo wada baxay Groupka A,ayaa soo tiigsaday fiinal
==========================================================================================
[2/10] Scraping: https://goobjoog.com/2020/10/25/xildhibaan-shaacir-guul-ayaan-u-rajaynaayaa-wasiir-xamsa-iyo-wasaarada-ciyaaraha-dalka/
Status: ok
Headline: Xildhibaan Shaacir "Guul Ayaan U Rajaynaayaa Wasiir Xamsa Iyo Wasaarada Ciyaaraha Dalka"
Body words: 179
Body preview: Xildhibaan Cabdullahi Maxamed Aadan (Shaacir) oo ka tirsan Xildhibaanada Golaha shacabka Baarlamaanka Soomaaliya horayna ugu mid ahaa xidigihii hore Soomaaliya ayaa u hambaleeyey Wasiirka Ciyaaraha iyo dhallinyarada Soomaaliya mudane Xamza Saciid Xam
Checkpoint saved: 2 rows -> goobjoog_ciyaaraha_scraped_articles_SAMPLE10.xlsx
==========================================================================================
[3/10] Scraping: https://goobjoog.com/2024/01/21/akhriso-tartanka-dowlad-goboleedyada-oo-dib-u-bilaabanaya-ogow-isku-aadka-iyo-waxkasta-oo-ku-saabsan-ila-aiyo-final-ka/
Status: ok
Headline: Akhriso: Tartanka Dowlad Goboleedyada oo Dib u Bilaabanaya, Ogow isku aadka iyo Waxkasta oo Ku Saabsan Ila aiyo Final-ka
Body words: 319
Body preview: Garoonka Kubadda Cagta ee Stadium Muqdisho waxa maanta dib uga bilaabanaya tartanka dowlad goboleedyada iyo gobolka Banaadir, kaas oo maalmihii lasoo dhaafay hakad galay, kadib dhacdadii ka dhalatay weerar lagu qaaday kooxdii ka socotay Koonfur Galbe
==========================================================================================
[4/10] Scraping: https://goobjoog.com/2020/07/11/maxamuud-maxamed-waxaan-diyaar-u-nahay-horomarka-iyo-kor-u-qaadida-ciyaaraha-degmada-diinsoor/
Status: ok
Headline: Maxamuud Maxamed "Waxaan Diyaar U Nahay Horomarka Iyo Kor U Qaadida Ciyaaraha Diinsoor "
Body words: 196
Body preview: Maamulka Ciyaaraha Degmada Diinsoor ayaa tartan u qabtay kooxaha ka dhisan degmadaas,iyagoo ugu magac daray is dhaxglka bulshada iyo nabadda degmada waxaan abaabulka tartankan iska kaashanaya dhallinyarada ka soo jeeda Diinsoor ee kala joogta gudaha
Checkpoint saved: 4 rows -> goobjoog_ciyaaraha_scraped_articles_SAMPLE10.xlsx
==========================================================================================
[5/10] Scraping: https://goobjoog.com/2019/06/10/wax-badan-ka-ogaw-kulanka-horseed-vs-muqdisho-city-club/
Status: ok
Headline: Wax Badan Ka Ogaw Kulanka Horseed VS Muqdisho City Club
Body words: 309
Body preview: Kooxda Ciidanka xooda dalka ee Horseed ayaa wajhaysa dhigeeda Muqdisho City Club oo sanadkii lasoo dhaafay ay wada ciyaareen kama dambeysta tartanka kubbadda cagta Jeneraal Daa'uud Cabdulle Xirse,inkastoo xidigaha M.C.C ay ku hanten Rigoorayaal,balse
==========================================================================================
[6/10] Scraping: https://goobjoog.com/2020/06/16/ibraahim-geedow-xiriirka-waa-in-uu-wakiilo-u-diraa-xirfadlayaasha-jooga-kenya/
Status: ok
Headline: Ibraahim Geedow "Xiriirka Kubbbadda CagtaS Soomaaliya Waa In Uu Wakiilo U Diraa Xirfadlayaasha Jooga Kenya "
Body words: 57
Body preview: Ibraahim Geedoow Cawaale oo ah qoraa iyo falanqeeye ciyaaraha gudaha ayaa sheegay Wadanka Kenya laga helayo ciyaartooy iyo macallimiin tayo wanaagsan kuwaas oo door wacan ka qaadan kara Xulka Qaranka wuxuuuna madaxda Xiriirka u sheegay in halkaas loo
Checkpoint saved: 6 rows -> goobjoog_ciyaaraha_scraped_articles_SAMPLE10.xlsx
==========================================================================================
[7/10] Scraping: https://goobjoog.com/2020/08/29/daadir-amiin-waan-ku-faraxsanahay-hanashada-horyaalka-heerka-labaad-ee-soomaaliya/
Status: ok
Headline: Daadir Amiin "Waan Ku Faraxsanahay Hanashada Horyaalka Heerka Koowaad Ee Soomaaliya "
Body words: 107
Body preview: Kooxda Geeska Afrika ayaa ku guulaystay horyaalka heerka ee kubbadda cagta Sooamaliya 2019-2020 waxaana guusha u qaaday tababarahooda Daadir Amiin Cali oo sidoo kale ah macallin ku xigeenka kooxda Dowladda hoose ee Muqdisho City Club. Daadir ayaa san
==========================================================================================
[8/10] Scraping: https://goobjoog.com/2019/03/28/hordhaca-horyaalka-somaaliya-yaa-guulo-badan-kooxaha-heegan-vs-dekedda/
Status: ok
Headline: Hordhaca Horyaalka Somaaliya-Yaa Guulo Badan Kooxaha Heegan VS Dekedda
Body words: 514
Body preview: Kooxda ciidan booliska Soomaaliyeed ee Heegan ayaa soo dhawaynaysa dhigeeda Dekedda oo ah naadiga difcaanaysa horyaalka labadii xili ciyaareed lasoo dhaafay wuxuuna kulan u yahay labada dhinac kulamadoodii 8-aad horyaalka Somalia Premier xili ciyaare
Checkpoint saved: 8 rows -> goobjoog_ciyaaraha_scraped_articles_SAMPLE10.xlsx
==========================================================================================
[9/10] Scraping: https://goobjoog.com/2019/11/21/daaru-tarbiya-oo-ku-guulaystay-horyaalka-tartanka-iskuulka-2019/
Status: ok
Headline: Daaru Tarbiya Oo Ku Guulaystay Tartanka Iskuulada
Body words: 225
Body preview: Waxaa lasoo gaba-gabeeyay koobkii kubbadda cagta dhallinyarada ee sanadka 2019-ka, waxaana ku guuleysatay kooxda Daaru Tarbiya [DT]. Tartanka dhallinyarada ayaa la qabtaa sanad kasta tan iyo markii uu billowday sanadkii 2016-kii wuxuuna tartankii soc
==========================================================================================
[10/10] Scraping: https://goobjoog.com/2019/09/28/guddoomiye-cabdiqani-saciid-xulka-dhallinyarada-waxaan-u-dirnay-waayo-aragnimo/
Status: ok
Headline: Guddoomiye Cabdiqani Saciid "Xulka Dhallinyarada Waxaan U Dirnay Waayo Aragnimo"
Body words: 334
Body preview: Xiriirka kubbadda cagta Bariga iyo Bartamaha Afrika ee Cecafa ayaa sanadkan markii ugu horeesay qabtay tartanka 15 Jirada Bariga iyo Bartamaha,iyadoo u jeedka ahaa in la horomariyo fursadano loo abuuro dhallinyarada iyo in aan qiyaano lagu samaynin d
Checkpoint saved: 10 rows -> goobjoog_ciyaaraha_scraped_articles_SAMPLE10.xlsx

==========================================================================================
Scraping complete. Saved 10 rows to goobjoog_ciyaaraha_scraped_articles_SAMPLE10.xlsx

Status counts:
status
ok    10
Name: count, dtype: int64

Body word count summary:
count     10.000000
mean     246.100000
std      129.941397
min       57.000000
25%      183.250000
50%      223.000000
75%      316.500000
max      514.000000
Name: body_word_count, dtype: float64

,url,headline,body_word_count,status,body
0,https://goobjoog.com/2020/12/31/yaa-guulaysan-...,Yaa Guulaysan Doono Gobolka Banaadir Iyo Galmu...,221,ok,Kooxaha Kubbadda Cagta Gobolka Banaadir iyo Ga...
1,https://goobjoog.com/2020/10/25/xildhibaan-sha...,"Xildhibaan Shaacir ""Guul Ayaan U Rajaynaayaa W...",179,ok,Xildhibaan Cabdullahi Maxamed Aadan (Shaacir) ...
2,https://goobjoog.com/2024/01/21/akhriso-tartan...,Akhriso: Tartanka Dowlad Goboleedyada oo Dib u...,319,ok,Garoonka Kubadda Cagta ee Stadium Muqdisho wax...
3,https://goobjoog.com/2020/07/11/maxamuud-maxam...,"Maxamuud Maxamed ""Waxaan Diyaar U Nahay Horoma...",196,ok,Maamulka Ciyaaraha Degmada Diinsoor ayaa tarta...
4,https://goobjoog.com/2019/06/10/wax-badan-ka-o...,Wax Badan Ka Ogaw Kulanka Horseed VS Muqdisho ...,309,ok,Kooxda Ciidanka xooda dalka ee Horseed ayaa wa...
5,https://goobjoog.com/2020/06/16/ibraahim-geedo...,"Ibraahim Geedow ""Xiriirka Kubbbadda CagtaS Soo...",57,ok,Ibraahim Geedoow Cawaale oo ah qoraa iyo falan...
6,https://goobjoog.com/2020/08/29/daadir-amiin-w...,"Daadir Amiin ""Waan Ku Faraxsanahay Hanashada H...",107,ok,Kooxda Geeska Afrika ayaa ku guulaystay horyaa...
7,https://goobjoog.com/2019/03/28/hordhaca-horya...,Hordhaca Horyaalka Somaaliya-Yaa Guulo Badan K...,514,ok,Kooxda ciidan booliska Soomaaliyeed ee Heegan ...
8,https://goobjoog.com/2019/11/21/daaru-tarbiya-...,Daaru Tarbiya Oo Ku Guulaystay Tartanka Iskuulada,225,ok,Waxaa lasoo gaba-gabeeyay koobkii kubbadda cag...
9,https://goobjoog.com/2019/09/28/guddoomiye-cab...,"Guddoomiye Cabdiqani Saciid ""Xulka Dhallinyara...",334,ok,Xiriirka kubbadda cagta Bariga iyo Bartamaha A...

In [2]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
import time
import os
from datetime import datetime
from urllib3.util.retry import Retry
from requests.adapters import HTTPAdapter

# =========================
# SETTINGS
# =========================

input_file = "goobjoog_ciyaaraha_links.xlsx"
output_file = "goobjoog_ciyaaraha_scraped_SAMPLE10.xlsx"

TEST_LIMIT = 10
SAVE_EVERY = 2
REQUEST_DELAY = 2.5

CATEGORY = "ciyaaro"
SOURCE = "Goobjoog"


# =========================
# SESSION
# =========================

def get_robust_session():
    session = requests.Session()

    retry = Retry(
        total=5,
        connect=5,
        read=5,
        backoff_factor=1.5,
        status_forcelist=[429, 500, 502, 503, 504],
        allowed_methods=["GET"],
        raise_on_status=False
    )

    adapter = HTTPAdapter(max_retries=retry)
    session.mount("http://", adapter)
    session.mount("https://", adapter)

    session.headers.update({
        "User-Agent": (
            "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
            "AppleWebKit/537.36 (KHTML, like Gecko) "
            "Chrome/124.0.0.0 Safari/537.36"
        ),
        "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8",
        "Accept-Language": "so,en-US;q=0.9,en;q=0.8",
        "Connection": "keep-alive",
    })

    return session


# =========================
# SCRAPER FUNCTIONS
# =========================

def extract_headline(soup):
    headline_tag = (
        soup.select_one("h1.entry-title")
        or soup.select_one("h1.post-title")
        or soup.find("h1")
    )

    if headline_tag:
        return headline_tag.get_text(" ", strip=True)

    return ""


def extract_body(soup):
    """
    No cleaning here.
    We only try to find the article container and collect paragraph text.
    If no article container is found, we fall back to all <p> tags.
    """

    article_div = (
        soup.select_one("div.entry-content")
        or soup.select_one("article div.entry-content")
        or soup.select_one("div.post-content")
        or soup.select_one("div.article-content")
        or soup.select_one("div.td-post-content")
        or soup.find("article")
        or soup.find("main")
    )

    if article_div:
        paragraphs = article_div.find_all("p")
    else:
        paragraphs = soup.find_all("p")

    body = "\n".join(
        p.get_text(" ", strip=True)
        for p in paragraphs
        if p.get_text(" ", strip=True)
    )

    return body


def scrape_goobjoog_article(url, session):
    try:
        response = session.get(url, timeout=25)

        if response.status_code != 200:
            return {
                "headline": "",
                "body": "",
                "status": f"failed_status_{response.status_code}",
                "error": f"HTTP status {response.status_code}"
            }

        soup = BeautifulSoup(response.content, "html.parser")

        headline = extract_headline(soup)
        body = extract_body(soup)

        if headline and body:
            status = "ok"
        elif headline and not body:
            status = "headline_only_no_body"
        elif body and not headline:
            status = "body_only_no_headline"
        else:
            status = "no_headline_no_body"

        return {
            "headline": headline,
            "body": body,
            "status": status,
            "error": ""
        }

    except Exception as e:
        return {
            "headline": "",
            "body": "",
            "status": "exception",
            "error": str(e)
        }


# =========================
# LOAD LINKS
# =========================

if not os.path.exists(input_file):
    raise FileNotFoundError(f"{input_file} not found. Put it in the same folder as this notebook/script.")

df_links = pd.read_excel(input_file)

print("Columns found in links file:")
print(df_links.columns.tolist())

if "URL" in df_links.columns:
    url_col = "URL"
elif "url" in df_links.columns:
    url_col = "url"
else:
    raise ValueError("No URL column found. Your file must contain either 'URL' or 'url'.")

urls_to_scrape = (
    df_links[url_col]
    .dropna()
    .astype(str)
    .str.strip()
    .drop_duplicates()
    .tolist()
)

urls_to_scrape = urls_to_scrape[:TEST_LIMIT]

print(f"\nSelected {len(urls_to_scrape)} URLs for sample scraping.")


# =========================
# CHECKPOINT / RESUME
# =========================

scraped_data = []
processed_urls = set()

if os.path.exists(output_file):
    df_existing = pd.read_excel(output_file)
    scraped_data = df_existing.to_dict("records")
    processed_urls = set(df_existing["url"].astype(str).tolist())

    print(f"\nResuming from checkpoint: {len(processed_urls)} URLs already scraped.")


# =========================
# MAIN LOOP
# =========================

session = get_robust_session()

print("\nStarting sample scrape...\n")

for i, url in enumerate(urls_to_scrape, start=1):
    if url in processed_urls:
        print(f"[{i}/{len(urls_to_scrape)}] Skipping already scraped: {url}")
        continue

    print("=" * 90)
    print(f"[{i}/{len(urls_to_scrape)}] Scraping: {url}")

    result = scrape_goobjoog_article(url, session)

    headline = result["headline"]
    body = result["body"]
    status = result["status"]
    error = result["error"]
    body_word_count = len(body.split()) if body else 0

    row = {
        "url": url,
        "headline": headline,
        "body": body,
        "category": CATEGORY,
        "source": SOURCE,
        "status": status,
        "body_word_count": body_word_count,
        "scraped_at": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "error": error
    }

    scraped_data.append(row)
    processed_urls.add(url)

    print(f"Status: {status}")
    print(f"Headline: {headline[:150] if headline else 'NO HEADLINE'}")
    print(f"Body words: {body_word_count}")
    print(f"Body preview: {body[:300].replace(chr(10), ' ') if body else 'NO BODY'}")

    if len(scraped_data) % SAVE_EVERY == 0:
        pd.DataFrame(scraped_data).to_excel(output_file, index=False)
        print(f"Checkpoint saved: {len(scraped_data)} rows -> {output_file}")

    time.sleep(REQUEST_DELAY)

# Final save
df_out = pd.DataFrame(scraped_data)
df_out.to_excel(output_file, index=False)

print("\n" + "=" * 90)
print(f"Sample scraping complete. Saved {len(df_out)} rows to {output_file}")

print("\nStatus counts:")
print(df_out["status"].value_counts(dropna=False))

print("\nBody word count summary:")
print(df_out["body_word_count"].describe())

df_out[["url", "headline", "body_word_count", "status", "body"]].head(10)

Columns found in links file:
['URL']

Selected 10 URLs for sample scraping.

Starting sample scrape...

==========================================================================================
[1/10] Scraping: https://goobjoog.com/2020/12/31/yaa-guulaysan-doono-gobolka-banaadir-iyo-galmudug-tartanka-maamul-goboleedyada-2020/
Status: ok
Headline: Yaa Guulaysan Doono Gobolka Banaadir Iyo Galmudug Tartanka Maamul Goboleedyada 2020
Body words: 224
Body preview: Kooxaha Kubbadda Cagta Gobolka Banaadir iyo Galmudug ayaa markii ugu horeesay wada dheeli doono heerka ugu danbeeya tartanka kubbadda cagta Maamul Goboleedyada iyo Gobolka Banaadir. Labada koox oo ka soo wada baxay Groupka A,ayaa soo tiigsaday fiinalaha tartan markii kowaad,tan iyo markii labilaaway
==========================================================================================
[2/10] Scraping: https://goobjoog.com/2020/10/25/xildhibaan-shaacir-guul-ayaan-u-rajaynaayaa-wasiir-xamsa-iyo-wasaarada-ciyaaraha-dalka/
Status: ok
Headline: Xildhibaan Shaacir “Guul Ayaan U Rajaynaayaa Wasiir Xamsa Iyo Wasaarada Ciyaaraha Dalka”
Body words: 179
Body preview: Xildhibaan Cabdullahi Maxamed Aadan (Shaacir) oo ka tirsan Xildhibaanada Golaha shacabka Baarlamaanka Soomaaliya horayna ugu mid ahaa xidigihii hore Soomaaliya ayaa u hambaleeyey Wasiirka Ciyaaraha iyo dhallinyarada Soomaaliya mudane Xamza Saciid Xamza ,isagoo sheegay in Wasiir Xamze uu yahay shaqsi
Checkpoint saved: 2 rows -> goobjoog_ciyaaraha_scraped_SAMPLE10.xlsx
==========================================================================================
[3/10] Scraping: https://goobjoog.com/2024/01/21/akhriso-tartanka-dowlad-goboleedyada-oo-dib-u-bilaabanaya-ogow-isku-aadka-iyo-waxkasta-oo-ku-saabsan-ila-aiyo-final-ka/
Status: ok
Headline: Akhriso: Tartanka Dowlad Goboleedyada oo Dib u Bilaabanaya, Ogow isku aadka iyo Waxkasta oo Ku Saabsan Ila aiyo Final-ka
Body words: 319
Body preview: Garoonka Kubadda Cagta ee Stadium Muqdisho waxa maanta dib uga bilaabanaya tartanka dowlad goboleedyada iyo gobolka Banaadir, kaas oo maalmihii lasoo dhaafay hakad galay, kadib dhacdadii ka dhalatay weerar lagu qaaday kooxdii ka socotay Koonfur Galbeed oo keentay in ay ka baxaan tartanka. Ciyaar la
==========================================================================================
[4/10] Scraping: https://goobjoog.com/2020/07/11/maxamuud-maxamed-waxaan-diyaar-u-nahay-horomarka-iyo-kor-u-qaadida-ciyaaraha-degmada-diinsoor/
Status: ok
Headline: Maxamuud Maxamed “Waxaan Diyaar U Nahay Horomarka Iyo Kor U Qaadida Ciyaaraha Diinsoor ”
Body words: 199
Body preview: Maamulka Ciyaaraha Degmada Diinsoor ayaa tartan u qabtay kooxaha ka dhisan degmadaas,iyagoo ugu magac daray is dhaxglka bulshada iyo nabadda degmada waxaan abaabulka tartankan iska kaashanaya dhallinyarada ka soo jeeda Diinsoor ee kala joogta gudaha Soomaaliya iyo dalka dibadiisa. “Anagoo kaashanayn
Checkpoint saved: 4 rows -> goobjoog_ciyaaraha_scraped_SAMPLE10.xlsx
==========================================================================================
[5/10] Scraping: https://goobjoog.com/2019/06/10/wax-badan-ka-ogaw-kulanka-horseed-vs-muqdisho-city-club/
Status: ok
Headline: Wax Badan Ka Ogaw Kulanka Horseed VS Muqdisho City Club
Body words: 320
Body preview: Kooxda Ciidanka xooda dalka ee Horseed ayaa wajhaysa dhigeeda Muqdisho City Club oo sanadkii lasoo dhaafay ay wada ciyaareen kama dambeysta tartanka kubbadda cagta Jeneraal Daa’uud Cabdulle Xirse,inkastoo xidigaha M.C.C ay ku hanten Rigoorayaal,balse kulanka waa is aragoodii 2aad horyaalka Somalia P
==========================================================================================
[6/10] Scraping: https://goobjoog.com/2020/06/16/ibraahim-geedow-xiriirka-waa-in-uu-wakiilo-u-diraa-xirfadlayaasha-jooga-kenya/
Status: ok
Headline: Ibraahim Geedow “Xiriirka Kubbbadda CagtaS Soomaaliya Waa In Uu Wakiilo U Diraa Xirfadlayaasha Jooga Kenya ”
Body words: 57
Body preview: Ibraahim Geedoow Cawaale oo ah qoraa iyo falanqeeye ciyaaraha gudaha ayaa sheegay Wadanka Kenya laga helayo ciyaartooy iyo macallimiin tayo wanaagsan kuwaas oo door wacan ka qaadan kara Xulka Qaranka wuxuuuna madaxda Xiriirka u sheegay in halkaas loo diro wakiilo soo fiiriyo xidigahaas. Halkan Ka Da
Checkpoint saved: 6 rows -> goobjoog_ciyaaraha_scraped_SAMPLE10.xlsx
==========================================================================================
[7/10] Scraping: https://goobjoog.com/2020/08/29/daadir-amiin-waan-ku-faraxsanahay-hanashada-horyaalka-heerka-labaad-ee-soomaaliya/
Status: ok
Headline: Daadir Amiin “Waan Ku Faraxsanahay Hanashada Horyaalka Heerka Koowaad Ee Soomaaliya ”
Body words: 110
Body preview: Kooxda Geeska Afrika ayaa ku guulaystay horyaalka heerka ee kubbadda cagta Sooamaliya 2019-2020 waxaana guusha u qaaday tababarahooda Daadir Amiin Cali oo sidoo kale ah macallin ku xigeenka kooxda Dowladda hoose ee Muqdisho City Club. Daadir ayaa sanadkan sameeyay guulo waaweyn waxaan u suurta gasha
==========================================================================================
[8/10] Scraping: https://goobjoog.com/2019/03/28/hordhaca-horyaalka-somaaliya-yaa-guulo-badan-kooxaha-heegan-vs-dekedda/
Status: ok
Headline: Hordhaca Horyaalka Somaaliya-Yaa Guulo Badan Kooxaha Heegan VS Dekedda
Body words: 523
Body preview: Kooxda ciidan booliska Soomaaliyeed ee Heegan ayaa soo dhawaynaysa dhigeeda Dekedda oo ah naadiga difcaanaysa horyaalka labadii xili ciyaareed lasoo dhaafay wuxuuna kulan u yahay labada dhinac kulamadoodii 8-aad horyaalka Somalia Premier xili ciyaareed 2018-2019. Xidigaha kooxda Heegan kulankii u da
Checkpoint saved: 8 rows -> goobjoog_ciyaaraha_scraped_SAMPLE10.xlsx
==========================================================================================
[9/10] Scraping: https://goobjoog.com/2019/11/21/daaru-tarbiya-oo-ku-guulaystay-horyaalka-tartanka-iskuulka-2019/
Status: ok
Headline: Daaru Tarbiya Oo Ku Guulaystay Tartanka Iskuulada
Body words: 225
Body preview: Waxaa lasoo gaba-gabeeyay koobkii kubbadda cagta dhallinyarada ee sanadka 2019-ka, waxaana ku guuleysatay kooxda Daaru Tarbiya [DT]. Tartanka dhallinyarada ayaa la qabtaa sanad kasta tan iyo markii uu billowday sanadkii 2016-kii wuxuuna tartankii socday bishii May ilaa November 2019. Kooxda DT ayaa
==========================================================================================
[10/10] Scraping: https://goobjoog.com/2019/09/28/guddoomiye-cabdiqani-saciid-xulka-dhallinyarada-waxaan-u-dirnay-waayo-aragnimo/
Status: ok
Headline: Guddoomiye Cabdiqani Saciid “Xulka Dhallinyarada Waxaan U Dirnay Waayo Aragnimo”
Body words: 337
Body preview: Xiriirka kubbadda cagta Bariga iyo Bartamaha Afrika ee Cecafa ayaa sanadkan markii ugu horeesay qabtay tartanka 15 Jirada Bariga iyo Bartamaha,iyadoo u jeedka ahaa in la horomariyo fursadano loo abuuro dhallinyarada iyo in aan qiyaano lagu samaynin da’daada kala gedisan tartamada soo socda ee Cecafa
Checkpoint saved: 10 rows -> goobjoog_ciyaaraha_scraped_SAMPLE10.xlsx

==========================================================================================
Sample scraping complete. Saved 10 rows to goobjoog_ciyaaraha_scraped_SAMPLE10.xlsx

Status counts:
status
ok    10
Name: count, dtype: int64

Body word count summary:
count     10.000000
mean     249.300000
std      132.306924
min       57.000000
25%      184.000000
50%      224.500000
75%      319.750000
max      523.000000
Name: body_word_count, dtype: float64

,url,headline,body_word_count,status,body
0,https://goobjoog.com/2020/12/31/yaa-guulaysan-...,Yaa Guulaysan Doono Gobolka Banaadir Iyo Galmu...,224,ok,Kooxaha Kubbadda Cagta Gobolka Banaadir iyo Ga...
1,https://goobjoog.com/2020/10/25/xildhibaan-sha...,Xildhibaan Shaacir “Guul Ayaan U Rajaynaayaa W...,179,ok,Xildhibaan Cabdullahi Maxamed Aadan (Shaacir) ...
2,https://goobjoog.com/2024/01/21/akhriso-tartan...,Akhriso: Tartanka Dowlad Goboleedyada oo Dib u...,319,ok,Garoonka Kubadda Cagta ee Stadium Muqdisho wax...
3,https://goobjoog.com/2020/07/11/maxamuud-maxam...,Maxamuud Maxamed “Waxaan Diyaar U Nahay Horoma...,199,ok,Maamulka Ciyaaraha Degmada Diinsoor ayaa tarta...
4,https://goobjoog.com/2019/06/10/wax-badan-ka-o...,Wax Badan Ka Ogaw Kulanka Horseed VS Muqdisho ...,320,ok,Kooxda Ciidanka xooda dalka ee Horseed ayaa wa...
5,https://goobjoog.com/2020/06/16/ibraahim-geedo...,Ibraahim Geedow “Xiriirka Kubbbadda CagtaS Soo...,57,ok,Ibraahim Geedoow Cawaale oo ah qoraa iyo falan...
6,https://goobjoog.com/2020/08/29/daadir-amiin-w...,Daadir Amiin “Waan Ku Faraxsanahay Hanashada H...,110,ok,Kooxda Geeska Afrika ayaa ku guulaystay horyaa...
7,https://goobjoog.com/2019/03/28/hordhaca-horya...,Hordhaca Horyaalka Somaaliya-Yaa Guulo Badan K...,523,ok,Kooxda ciidan booliska Soomaaliyeed ee Heegan ...
8,https://goobjoog.com/2019/11/21/daaru-tarbiya-...,Daaru Tarbiya Oo Ku Guulaystay Tartanka Iskuulada,225,ok,Waxaa lasoo gaba-gabeeyay koobkii kubbadda cag...
9,https://goobjoog.com/2019/09/28/guddoomiye-cab...,Guddoomiye Cabdiqani Saciid “Xulka Dhallinyara...,337,ok,Xiriirka kubbadda cagta Bariga iyo Bartamaha A...

In [3]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
import time
import os
from datetime import datetime
from urllib3.util.retry import Retry
from requests.adapters import HTTPAdapter

# =========================
# SETTINGS
# =========================

input_file = "goobjoog_ciyaaraha_links.xlsx"
output_file = "goobjoog_ciyaaraha_scraped_articles_FIXED.xlsx"

TEST_LIMIT = None      # None = scrape all links
SAVE_EVERY = 5         # Save checkpoint every 5 articles
REQUEST_DELAY = 2.5    # Delay between requests

CATEGORY = "ciyaaro"
SOURCE = "Goobjoog"


# =========================
# SESSION
# =========================

def get_robust_session():
    session = requests.Session()

    retry = Retry(
        total=5,
        connect=5,
        read=5,
        backoff_factor=1.5,
        status_forcelist=[429, 500, 502, 503, 504],
        allowed_methods=["GET"],
        raise_on_status=False
    )

    adapter = HTTPAdapter(max_retries=retry)
    session.mount("http://", adapter)
    session.mount("https://", adapter)

    session.headers.update({
        "User-Agent": (
            "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
            "AppleWebKit/537.36 (KHTML, like Gecko) "
            "Chrome/124.0.0.0 Safari/537.36"
        ),
        "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8",
        "Accept-Language": "so,en-US;q=0.9,en;q=0.8",
        "Connection": "keep-alive",
    })

    return session


# =========================
# SCRAPER FUNCTIONS
# =========================

def extract_headline(soup):
    headline_tag = (
        soup.select_one("h1.entry-title")
        or soup.select_one("h1.post-title")
        or soup.find("h1")
    )

    if headline_tag:
        return headline_tag.get_text(" ", strip=True)

    return ""


def extract_body(soup):
    """
    No cleaning here.
    This only extracts paragraph text from the best available article container.
    If no article container is found, it falls back to all <p> tags.
    """

    article_div = (
        soup.select_one("div.entry-content")
        or soup.select_one("article div.entry-content")
        or soup.select_one("div.post-content")
        or soup.select_one("div.article-content")
        or soup.select_one("div.td-post-content")
        or soup.find("article")
        or soup.find("main")
    )

    if article_div:
        paragraphs = article_div.find_all("p")
    else:
        paragraphs = soup.find_all("p")

    body = "\n".join(
        p.get_text(" ", strip=True)
        for p in paragraphs
        if p.get_text(" ", strip=True)
    )

    return body


def scrape_goobjoog_article(url, session):
    try:
        response = session.get(url, timeout=25)

        if response.status_code != 200:
            return {
                "headline": "",
                "body": "",
                "status": f"failed_status_{response.status_code}",
                "error": f"HTTP status {response.status_code}"
            }

        soup = BeautifulSoup(response.content, "html.parser")

        headline = extract_headline(soup)
        body = extract_body(soup)

        if headline and body:
            status = "ok"
        elif headline and not body:
            status = "headline_only_no_body"
        elif body and not headline:
            status = "body_only_no_headline"
        else:
            status = "no_headline_no_body"

        return {
            "headline": headline,
            "body": body,
            "status": status,
            "error": ""
        }

    except Exception as e:
        return {
            "headline": "",
            "body": "",
            "status": "exception",
            "error": str(e)
        }


# =========================
# LOAD LINKS
# =========================

if not os.path.exists(input_file):
    raise FileNotFoundError(
        f"{input_file} not found. Put it in the same folder as this notebook/script."
    )

df_links = pd.read_excel(input_file)

print("Columns found in links file:")
print(df_links.columns.tolist())

if "URL" in df_links.columns:
    url_col = "URL"
elif "url" in df_links.columns:
    url_col = "url"
else:
    raise ValueError("No URL column found. Your file must contain either 'URL' or 'url'.")

urls_to_scrape = (
    df_links[url_col]
    .dropna()
    .astype(str)
    .str.strip()
    .drop_duplicates()
    .tolist()
)

if TEST_LIMIT is not None:
    urls_to_scrape = urls_to_scrape[:TEST_LIMIT]

print(f"\nTotal URLs selected for scraping: {len(urls_to_scrape)}")


# =========================
# CHECKPOINT / RESUME
# =========================

scraped_data = []
processed_urls = set()

if os.path.exists(output_file):
    df_existing = pd.read_excel(output_file)

    if not df_existing.empty and "url" in df_existing.columns:
        scraped_data = df_existing.to_dict("records")
        processed_urls = set(df_existing["url"].astype(str).tolist())

        print(f"\nResuming from checkpoint: {len(processed_urls)} URLs already scraped.")
    else:
        print("\nExisting output file found, but it is empty or invalid. Starting fresh.")


# =========================
# MAIN LOOP
# =========================

session = get_robust_session()

print("\nStarting full Goobjoog Ciyaaro scrape...\n")

for i, url in enumerate(urls_to_scrape, start=1):
    if url in processed_urls:
        print(f"[{i}/{len(urls_to_scrape)}] Skipping already scraped: {url}")
        continue

    print("=" * 90)
    print(f"[{i}/{len(urls_to_scrape)}] Scraping: {url}")

    result = scrape_goobjoog_article(url, session)

    headline = result["headline"]
    body = result["body"]
    status = result["status"]
    error = result["error"]
    body_word_count = len(body.split()) if body else 0

    row = {
        "url": url,
        "headline": headline,
        "body": body,
        "category": CATEGORY,
        "source": SOURCE,
        "status": status,
        "body_word_count": body_word_count,
        "scraped_at": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "error": error
    }

    scraped_data.append(row)
    processed_urls.add(url)

    print(f"Status: {status}")
    print(f"Headline: {headline[:150] if headline else 'NO HEADLINE'}")
    print(f"Body words: {body_word_count}")
    print(f"Body preview: {body[:300].replace(chr(10), ' ') if body else 'NO BODY'}")

    if len(scraped_data) % SAVE_EVERY == 0:
        pd.DataFrame(scraped_data).to_excel(output_file, index=False)
        print(f"Checkpoint saved: {len(scraped_data)} rows -> {output_file}")

    time.sleep(REQUEST_DELAY)


# =========================
# FINAL SAVE + SUMMARY
# =========================

df_out = pd.DataFrame(scraped_data)
df_out.to_excel(output_file, index=False)

print("\n" + "=" * 90)
print(f"Full scraping complete. Saved {len(df_out)} rows to {output_file}")

print("\nStatus counts:")
print(df_out["status"].value_counts(dropna=False))

print("\nBody word count summary:")
print(df_out["body_word_count"].describe())

print("\nRows with no body or very short body:")
display(
    df_out[
        (df_out["body"].fillna("").str.strip() == "") |
        (df_out["body_word_count"] < 50)
    ][["url", "headline", "body_word_count", "status", "error"]].head(20)
)

display(df_out[["url", "headline", "body_word_count", "status", "body"]].head(10))

Columns found in links file:
['URL']

Total URLs selected for scraping: 674

Starting full Goobjoog Ciyaaro scrape...

==========================================================================================
[1/674] Scraping: https://goobjoog.com/2020/12/31/yaa-guulaysan-doono-gobolka-banaadir-iyo-galmudug-tartanka-maamul-goboleedyada-2020/
Status: ok
Headline: Yaa Guulaysan Doono Gobolka Banaadir Iyo Galmudug Tartanka Maamul Goboleedyada 2020
Body words: 224
Body preview: Kooxaha Kubbadda Cagta Gobolka Banaadir iyo Galmudug ayaa markii ugu horeesay wada dheeli doono heerka ugu danbeeya tartanka kubbadda cagta Maamul Goboleedyada iyo Gobolka Banaadir. Labada koox oo ka soo wada baxay Groupka A,ayaa soo tiigsaday fiinalaha tartan markii kowaad,tan iyo markii labilaaway
==========================================================================================
[2/674] Scraping: https://goobjoog.com/2020/10/25/xildhibaan-shaacir-guul-ayaan-u-rajaynaayaa-wasiir-xamsa-iyo-wasaarada-ciyaaraha-dalka/
Status: ok
Headline: Xildhibaan Shaacir “Guul Ayaan U Rajaynaayaa Wasiir Xamsa Iyo Wasaarada Ciyaaraha Dalka”
Body words: 179
Body preview: Xildhibaan Cabdullahi Maxamed Aadan (Shaacir) oo ka tirsan Xildhibaanada Golaha shacabka Baarlamaanka Soomaaliya horayna ugu mid ahaa xidigihii hore Soomaaliya ayaa u hambaleeyey Wasiirka Ciyaaraha iyo dhallinyarada Soomaaliya mudane Xamza Saciid Xamza ,isagoo sheegay in Wasiir Xamze uu yahay shaqsi
==========================================================================================
[3/674] Scraping: https://goobjoog.com/2024/01/21/akhriso-tartanka-dowlad-goboleedyada-oo-dib-u-bilaabanaya-ogow-isku-aadka-iyo-waxkasta-oo-ku-saabsan-ila-aiyo-final-ka/
Status: ok
Headline: Akhriso: Tartanka Dowlad Goboleedyada oo Dib u Bilaabanaya, Ogow isku aadka iyo Waxkasta oo Ku Saabsan Ila aiyo Final-ka
Body words: 319
Body preview: Garoonka Kubadda Cagta ee Stadium Muqdisho waxa maanta dib uga bilaabanaya tartanka dowlad goboleedyada iyo gobolka Banaadir, kaas oo maalmihii lasoo dhaafay hakad galay, kadib dhacdadii ka dhalatay weerar lagu qaaday kooxdii ka socotay Koonfur Galbeed oo keentay in ay ka baxaan tartanka. Ciyaar la
==========================================================================================
[4/674] Scraping: https://goobjoog.com/2020/07/11/maxamuud-maxamed-waxaan-diyaar-u-nahay-horomarka-iyo-kor-u-qaadida-ciyaaraha-degmada-diinsoor/
Status: ok
Headline: Maxamuud Maxamed “Waxaan Diyaar U Nahay Horomarka Iyo Kor U Qaadida Ciyaaraha Diinsoor ”
Body words: 199
Body preview: Maamulka Ciyaaraha Degmada Diinsoor ayaa tartan u qabtay kooxaha ka dhisan degmadaas,iyagoo ugu magac daray is dhaxglka bulshada iyo nabadda degmada waxaan abaabulka tartankan iska kaashanaya dhallinyarada ka soo jeeda Diinsoor ee kala joogta gudaha Soomaaliya iyo dalka dibadiisa. “Anagoo kaashanayn
==========================================================================================
[5/674] Scraping: https://goobjoog.com/2019/06/10/wax-badan-ka-ogaw-kulanka-horseed-vs-muqdisho-city-club/
Status: ok
Headline: Wax Badan Ka Ogaw Kulanka Horseed VS Muqdisho City Club
Body words: 320
Body preview: Kooxda Ciidanka xooda dalka ee Horseed ayaa wajhaysa dhigeeda Muqdisho City Club oo sanadkii lasoo dhaafay ay wada ciyaareen kama dambeysta tartanka kubbadda cagta Jeneraal Daa’uud Cabdulle Xirse,inkastoo xidigaha M.C.C ay ku hanten Rigoorayaal,balse kulanka waa is aragoodii 2aad horyaalka Somalia P
Checkpoint saved: 5 rows -> goobjoog_ciyaaraha_scraped_articles_FIXED.xlsx
==========================================================================================
[6/674] Scraping: https://goobjoog.com/2020/06/16/ibraahim-geedow-xiriirka-waa-in-uu-wakiilo-u-diraa-xirfadlayaasha-jooga-kenya/
Status: ok
Headline: Ibraahim Geedow “Xiriirka Kubbbadda CagtaS Soomaaliya Waa In Uu Wakiilo U Diraa Xirfadlayaasha Jooga Kenya ”
Body words: 57
Body preview: Ibraahim Geedoow Cawaale oo ah qoraa iyo falanqeeye ciyaaraha gudaha ayaa sheegay Wadanka Kenya laga helayo ciyaartooy iyo macallimiin tayo wanaagsan kuwaas oo door wacan ka qaadan kara Xulka Qaranka wuxuuuna madaxda Xiriirka u sheegay in halkaas loo diro wakiilo soo fiiriyo xidigahaas. Halkan Ka Da
==========================================================================================
[7/674] Scraping: https://goobjoog.com/2020/08/29/daadir-amiin-waan-ku-faraxsanahay-hanashada-horyaalka-heerka-labaad-ee-soomaaliya/
Status: ok
Headline: Daadir Amiin “Waan Ku Faraxsanahay Hanashada Horyaalka Heerka Koowaad Ee Soomaaliya ”
Body words: 110
Body preview: Kooxda Geeska Afrika ayaa ku guulaystay horyaalka heerka ee kubbadda cagta Sooamaliya 2019-2020 waxaana guusha u qaaday tababarahooda Daadir Amiin Cali oo sidoo kale ah macallin ku xigeenka kooxda Dowladda hoose ee Muqdisho City Club. Daadir ayaa sanadkan sameeyay guulo waaweyn waxaan u suurta gasha
==========================================================================================
[8/674] Scraping: https://goobjoog.com/2019/03/28/hordhaca-horyaalka-somaaliya-yaa-guulo-badan-kooxaha-heegan-vs-dekedda/
Status: ok
Headline: Hordhaca Horyaalka Somaaliya-Yaa Guulo Badan Kooxaha Heegan VS Dekedda
Body words: 523
Body preview: Kooxda ciidan booliska Soomaaliyeed ee Heegan ayaa soo dhawaynaysa dhigeeda Dekedda oo ah naadiga difcaanaysa horyaalka labadii xili ciyaareed lasoo dhaafay wuxuuna kulan u yahay labada dhinac kulamadoodii 8-aad horyaalka Somalia Premier xili ciyaareed 2018-2019. Xidigaha kooxda Heegan kulankii u da
==========================================================================================
[9/674] Scraping: https://goobjoog.com/2019/11/21/daaru-tarbiya-oo-ku-guulaystay-horyaalka-tartanka-iskuulka-2019/
Status: ok
Headline: Daaru Tarbiya Oo Ku Guulaystay Tartanka Iskuulada
Body words: 225
Body preview: Waxaa lasoo gaba-gabeeyay koobkii kubbadda cagta dhallinyarada ee sanadka 2019-ka, waxaana ku guuleysatay kooxda Daaru Tarbiya [DT]. Tartanka dhallinyarada ayaa la qabtaa sanad kasta tan iyo markii uu billowday sanadkii 2016-kii wuxuuna tartankii socday bishii May ilaa November 2019. Kooxda DT ayaa
==========================================================================================
[10/674] Scraping: https://goobjoog.com/2019/09/28/guddoomiye-cabdiqani-saciid-xulka-dhallinyarada-waxaan-u-dirnay-waayo-aragnimo/
Status: ok
Headline: Guddoomiye Cabdiqani Saciid “Xulka Dhallinyarada Waxaan U Dirnay Waayo Aragnimo”
Body words: 337
Body preview: Xiriirka kubbadda cagta Bariga iyo Bartamaha Afrika ee Cecafa ayaa sanadkan markii ugu horeesay qabtay tartanka 15 Jirada Bariga iyo Bartamaha,iyadoo u jeedka ahaa in la horomariyo fursadano loo abuuro dhallinyarada iyo in aan qiyaano lagu samaynin da’daada kala gedisan tartamada soo socda ee Cecafa
Checkpoint saved: 10 rows -> goobjoog_ciyaaraha_scraped_articles_FIXED.xlsx
==========================================================================================
[11/674] Scraping: https://goobjoog.com/2019/05/23/wax-ka-ogow-qaabka-ay-u-tababartaan-goolhayaasha-kooxaha-kubbadda-cagta-soomaaliya/
Status: ok
Headline: Wax Ka Ogow Qaabka Ay U Tababartaan Goolhayaasha Kooxaha Kubbadda Cagta Soomaaliya
Body words: 217
Body preview: Shaqada goolhaya ma ahan mid fudud waxa ay ka mid tahay tan ugu adag ay qabtaan dadka bartay xirfadan qubarada ciyaaraha waxa ku sheegaan in goohayaha uu kaalin weyn ay ku lee yihiin ciyaaraha kubbadda cagta. Macalimiinta farsamada u qaabilsan goolhayaasha Xiriirka kubbadda cagta ayaa da’daal badan
==========================================================================================
[12/674] Scraping: https://goobjoog.com/2021/01/14/guddoomiyaha-xiriirka-kubbadda-cagta-galmudug-oo-si-diiran-loogu-soo-dhaweeyay-magaalada-cadaado/
Status: ok
Headline: Guddoomiyaha Xiriirka Kubbadda Cagta Galmudug Oo Si Diiran Loogu Soo Dhaweeyay Magaalada Cadaado
Body words: 202
Body preview: Guddoomiyaha Xiriirka Kubbadda Cagta Galmudug mudane Xasan Axmed Shire oo safar shaqo ku joogay magaalada Muqdisho tan iyo bishii December 2020 ayaa si weyn loogu soo dhaweeyay magaalada Cadaado ee Maamulka Galmudug,waxaana soo dhaweyntiisa ka qeyb galay bahda ciyaaraha Galmudug iyo bulshada qeybahe
==========================================================================================
[13/674] Scraping: https://goobjoog.com/2019/05/18/macalin-tareexidigaha-xulka-qaranka-waxa-ay-soo-bandhigeen-qaab-ciyaareed-aad-u-wanaagsan/
Status: ok
Headline: Macalin Taree“Xidigaha Xulka Qaranka Waxa Ay Soo Bandhigeen Qaab Ciyaareed Aad U Wanaagsan”
Body words: 128
Body preview: Ciyaartooyda xulka qaranka Soomaaliya oo isu diyaarinaya ka qeyb galka tartamo kala duwan ee sanada 2019 ayaa todobaadyadii lasoo dhaafay ciyaaro saaxiibtinimo la dheelay kooxaha waaweyn ee kubbadda cagta,iyagoo inta badan guulo waaweyn ka gaaray kulamadii saaxiibtinimo ee loo qorsheeyay. Macalmiint
==========================================================================================
[14/674] Scraping: https://goobjoog.com/2019/04/20/xiriirka-cayaaraha-fudud-oo-ka-qayb-galay-shirwaynaha-28-aad-ee-qaaradda-afrika/
Status: ok
Headline: Xiriirka Cayaaraha Fudud Oo Ka Qayb Galay Shirwaynaha 28-aad Ee Qaaradda Afrika
Body words: 193
Body preview: magaalada Abidjan ee caasimadda dalka Ivory Coast waxaa ka dhacday shirwaynaha 28 ee xiriirada Cayaaraha Fudud ee qaaradda Afrika kaasoo lagu dooranayay hogaanka cayaaraha fudud ee qaaradda. Dooraashan waxaa Soomaaliya uga qayb galay Guddoomiyaha Xiriirka cayaaraha Fudud Drs Khadiijo Aadan Daahir,wa
==========================================================================================
[15/674] Scraping: https://goobjoog.com/2020/06/13/yuusuf-yuusuf-wasiir-khadiijo-qalad-ayay-ku-haystaa-warbaahinta-goobjoog/
Status: ok
Headline: Yuusuf Yuusuf  “ Wasiir Khadiijo Qalad Ayay Ku Haystaa Warbaahinta Goobjoog ”
Body words: 49
Body preview: Yuusuf Maxamed Yuusuf oo ah qoraa xaga ciyaaraha ayaa sheegay in Wasiirka ciyaaraha iyo dhallinyarada Dowladda Khadiijo Maxamed Diiriye iyo xiriirada ka dhisan Soomaaliya aysan xaq u laheyn in garoomada ciyaaraha aysan ka celin karin warbaahinta iyo muwaadintiinta. Halkan Ka Daawo Qoraa Yuusuf Yuusu
Checkpoint saved: 15 rows -> goobjoog_ciyaaraha_scraped_articles_FIXED.xlsx
==========================================================================================
[16/674] Scraping: https://goobjoog.com/2019/08/21/kooxda-horseed-oo-la-balansan-al-rifaa-sports-club/
Status: ok
Headline: Kooxda Horseed Oo La Balansan Al Rifaa  Sports Club
Body words: 298
Body preview: Kooxda Horseed ee ciidanka xogga dalka ayaa ciyaaraysa kulankii labaad ee tartanka Mohamed VI Champions 2019 ,iyadoo la balansan kooxda reer Baxreen ee Al-Riffa Sports Club. 18 Bishan ayuu tartanka ka furmay magaalada Casabalnca ee wadanka Morocco ,iyadoo ciyaarta furitaanka ay wada dheeleen Horseed
==========================================================================================
[17/674] Scraping: https://goobjoog.com/2019/10/05/maxaa-kala-socotaa-dhacdooyinkii-ugu-waaweynaa-ee-dhacay-bisha-september-ciyaaraha-soomaaliya/
Status: ok
Headline: Maxaa Kala Socotaa Dhacdooyinkii Ugu Waaweynaa Ee Dhacay  Bisha September Ciyaaraha Soomaaliya
Body words: 1106
Body preview: 01-September 2019- Daa’uud Cabdullahi Tubaal oo ka tirsan kooxda Dekeddaha ayaa loo magacaabay macallinka kooxda kubbadda cagta Degmada Yaaqshiid ee Gobolka Banaadir waxayna u aheyd markii ugu horeesay oo laacibkan loo magacaabo xili tababarnimo. 02-September 2019- Garoonka Cawaale ee magaalada Gaal
==========================================================================================
[18/674] Scraping: https://goobjoog.com/2018/12/02/imaatinka-kooxda-melbourne-labadii-sano-ee-lasoo-dhaafay-waxa-ay-gogol-xaar-u-noqotay-goolkii-uu-laaciib-feysal-xasan-axmed-ka-dhaliyay-xulka-ethiopia/
Status: ok
Headline: Imaatinka kooxda Melbourne Labadii sano Ee Lasoo Dhaafay Waxa ay go’gol Xaar U Noqotay Goolkii uu Laaciib Feysal Xasan Axmed Ka dhaliyay Xulka Ethiopi
Body words: 288
Body preview: La taliyahay arimaha isboortiga Gobolka Banaadir Cabdiqaadir Muxidiin Xaaji (Dacar) oo marti ku ahaa Barnaamijka Xeyndaabka ciyaaraha Goobjoog TV ayaa sheegay qurbajoogta dalka u imaanaysa ciyaaraha saaxiibtinimo iyo is dhaxgalka bulshada laga faa’idayo waxyaalo badan oo dalka u ah wanaag iyo horoma
==========================================================================================
[19/674] Scraping: https://goobjoog.com/2019/09/19/ogow-sida-loo-diyaariyay-xulka-dhalinyarada-soomaaliya-wajiga-kowaad/
Status: ok
Headline: Ogow Sida Loo Diyaariyay Xulka Dhalinyarada Soomaaliya
Body words: 646
Body preview: Madaxda xariirka kubbadda cagta kubbadda cagta Soomaaliya ayaa juhdi iyo waqti badan ku bixiyay dhisidda da’yarta xulkeena oo markii ugu horeesay ka qeyb galay ciyaaraha 15 Jirada Bariga iyo Bartamaha Africa 2019. 21-July 2019- Waxaada dhallinyarada xariirka Soomaaliyeed ee kubbadda cagta ayaa xidig
==========================================================================================
[20/674] Scraping: https://goobjoog.com/2020/12/20/tartanka-maamul-goboleedyada-iyo-gobolka-banaadir-oo-maanta-ka-furmaya-magaalada-muqdisho/
Status: ok
Headline: Tartanka Maamul Goboleedyada Iyo Gobolka Banaadir Oo Maanta Ka Furmaya Magaalada Muqdisho
Body words: 171
Body preview: Tartanka Kubadda Cagta Maamul Goboleedyada iyo Gobolka Banaadir 2020 ayaa ka furmaya Magaalada Muqdisho,waxaana ciyaarta ugu horeesa wada dheeli doono kooxaha Gobolka Banaadir iyo Galamudug oo kuwada jira Group A,waana markii ugu horeesay ay tartanka isku arkayaan labada dhinac. Kooxda Gobolka Banaa
Checkpoint saved: 20 rows -> goobjoog_ciyaaraha_scraped_articles_FIXED.xlsx
==========================================================================================
[21/674] Scraping: https://goobjoog.com/2018/11/14/natiijo-maxay-kusoo-dhmaatay-ciyaartii-u-dhaxeeysay-dalalka-soomaaliya-iyo-ethiopia/
Status: headline_only_no_body
Headline: Natiijo:-Maxay Kusoo Dhmaatay Ciyaartii U Dhaxeeysay Dalalka Soomaaliya Iyo Ethiopia
Body words: 0
Body preview: NO BODY
==========================================================================================
[22/674] Scraping: https://goobjoog.com/2019/04/24/kooxda-muqdisho-city-club-oo-guul-ku-bilaawday-wareega-2aad-ee-horyaalka-soomaaliya/
Status: ok
Headline: Kooxda Muqdisho City Club Oo Guul Ku Bilaawday Wareega 2aad Ee Horyaalka Soomaaliya
Body words: 258
Body preview: Kooxaha kubbadda cagta Muqdisho City Club iyo L.L.P Jeenyo ayaa wada dheelay kulamoodii 10-aad horyaalka Soomaaliya iyo gudd ahaa ciyaartii 47aad xili ciyaareedka 2018-2019. Qeybta 1aad labada koox ayaa soo bandhigay ciyaar ku dheehan weerar iyo weerar celis,balse waxaa lagu kala nastay barbaro gool
==========================================================================================
[23/674] Scraping: https://goobjoog.com/2020/10/29/yoonis-faarax-oo-lagu-soo-dhaweeyay-dalka-sweden/
Status: ok
Headline: Yoonis Faarax Oo Lagu Soo Dhaweeyay Dalka Sweden
Body words: 225
Body preview: Laacibka Xulka Qaranka Soomaaliya Yoonis Cabdirisaaq Faarax ayaa gaaray magaalada Stockholm ee dalka Sweden,waxaan si weyn halkaa ugu soo dhaweyay qaar ka mid ah bahda isboortiga iyo laacibiintii Xulka Qaranka Soomaaliya. Yoonis Faarax oo ka mid ahaa xidigihii kaalinta wanaagsan ka qaatay guulihii X
==========================================================================================
[24/674] Scraping: https://goobjoog.com/2020/02/03/gudd-cabdiqani-madaxweyne-deni-wuxuu-diyaar-u-yahay-horomarinta-garoomada-kubbadda-cagta-puntland/
Status: ok
Headline: GUDD.Cabdiqani “Madaxweyne Deni Wuxuu Diyaar U Yahay Horomarinta Garoomada Kubbadda Cagta Puntland”
Body words: 214
Body preview: Bishii May 2019 guddoomiyaha Xiriirka Kubbadda Cagta Soomaaliya Cabdiqani Saciid Carab iyo wafdi la socday ayaa safar shaqo ku tagay magaalada Garoowe ee Gobolka Nugaal wuxuuna socdaalkooda ahaa kormeerida iyo dib u dayactirka ka socda garoomada kubbadda cagta maamulka Puntland. “Safarkeenii Puntlan
==========================================================================================
[25/674] Scraping: https://goobjoog.com/2019/09/25/ogow-xogta-kulanka-soomaaliya-koonfurta/
Status: ok
Headline: Ogow Xogta Kulanka Soomaaliya & Koonfurta
Body words: 131
Body preview: 20 Jirada Soomaaliya iyo Koonfurta Sudan ayaa kulan xiiso badan oo ka tirsan tartanka Bariga iyo Bartamaha Afrika 2019 ku leh garoonka Njeru ee wadanka Uganda. Soomaaliya kulankii furitaanka ciyaaraha 20 jirada Barig iyo Bartamaha Afrika 2019 waxa ay guul daro 2-1 kasoo gaartay xulka Burundi waxaana
Checkpoint saved: 25 rows -> goobjoog_ciyaaraha_scraped_articles_FIXED.xlsx
==========================================================================================
[26/674] Scraping: https://goobjoog.com/2018/10/09/yarisow-stadium-muqdisho-waxaan-ku-qabaneynaa-tartanka-maamul-goboleedyada-2018/
Status: ok
Headline: Yarisow: Stadium Muqdisho waxaan ku qabaneynaa Tartanka Maamul Goboleedyada 2018
Body words: 251
Body preview: Gudoomiyaha Gobolka Banaadir ahna duqa caasimada Muqdisho Cabdiraxmaan Cumar Cusmaan (Eng.Yariisow) ayaa sheegay in maamulkiisa xooga saarayo labada bil ee ka harsan sanadkan 2018 sidii loogu diyaari garoobi lahaa in Stadium Muqdisho uu marti geliyo qabashada tartanka kubbadda cagta Maamul-Goboleedy
==========================================================================================
[27/674] Scraping: https://goobjoog.com/2020/05/18/xasan-yabarow-wiish-isbadal-guud-ayaan-ku-samaynayaan-gasrooka-kubbadda-cagta-soomaaliya/
Status: ok
Headline: Xasan Yabarow Wiish “Isbadal Guud Ayaan Ku Samaynaynaa Garsooka Kubbadda Cagta ”
Body words: 331
Body preview: Guddoomiyahay gudiga garsoorka kubbadda cagta Soomaaliya Xasan Yabarow Wiish ayaa sheegay in uu is badal iyo dib habeyn uu ku sameyn doono waxaada garsoorka Xiriirka Kubbadda Cagta. “Tani iyo markii la ii magacaabay jagadan waxaan kordhinay horomarinta aqoonta garsooryaasha, welina waxaan ku jirnaa
==========================================================================================
[28/674] Scraping: https://goobjoog.com/2020/06/17/115211-2/
Status: ok
Headline: Tartan Lagu Xusayo Laacibkii Hore LLp Jeenyo Iyo Xulka Qaranka Marxuum Maxamed Xaaji Aadam (Uurey) Ayaa Si Weyn Ugu Socda Muqdisho
Body words: 193
Body preview: Magaalada Muqdisho waxaa si weyn ugu socda tartan lagu xusayo laacibkii hore LLP Jeenyo Xulka Qranka Soomaaliya iyo Gobolka Baayo Maxamaed Xaaji Adam Uurey kaas oo dabayaaqadii 2019 ku geeriyooday magaalada Toronto ee Wadanka Canada. Tartanka lagu xusayo laacibkii hore Xulka Qaranka marxuum Uurey wa
==========================================================================================
[29/674] Scraping: https://goobjoog.com/2021/03/28/pep-guardiola-dabada-ayuu-naga-laadi-jiray-tababar-walba-thomas-muller/
Status: ok
Headline: “Pep Guardiola dabada ayuu naga laadi jiray tababar walba” – Thomas Muller
Body words: 172
Body preview: Weeraryahanka kooxda Bayern Munich ee Thomas Muller ayaa ka sheekeeyay ka hoos shaqeynta Tababare Pep Guardiola iyo xeeladihii uu sameyn jiray markii uu macallinka u ahaa Bavarians. Muller ayaa soo hadal qaaday qaabkii uu Guardiola u sameysan jiray tababarka iyo sida uu u dhiiro gelin jiray xiddigah
==========================================================================================
[30/674] Scraping: https://goobjoog.com/2019/11/18/kooxda-melbourne-oo-sanaadkii-afaraad-dalka-imaanaysa-is-dhaxgal-bulsho/
Status: ok
Headline: Kooxda Melbourne Oo Sanaadkii Afaraad Dalka Imaanaysa
Body words: 239
Body preview: Kooxda Jaaliya Soomaaliyeed ee Melboune ayaa sanadkii afaraad dalka u imaanaya ciyaaraha saaxiibtinimo iyo is dhaxgal bulsho,iyagoo sanadkii lasoo dhaafay 2018 booqashooyin ku maray Gobolka Banaadir,Jubaland iyo Koonfur Galbeed waxaana socdaalka kooxdan sanad walib suga dhallinyarada. Guddoomiyaha X
Checkpoint saved: 30 rows -> goobjoog_ciyaaraha_scraped_articles_FIXED.xlsx

,url,headline,body_word_count,status,error
14,https://goobjoog.com/2020/06/13/yuusuf-yuusuf-...,Yuusuf Yuusuf “ Wasiir Khadiijo Qalad Ayay Ku...,49,ok,
20,https://goobjoog.com/2018/11/14/natiijo-maxay-...,Natiijo:-Maxay Kusoo Dhmaatay Ciyaartii U Dhax...,0,headline_only_no_body,
40,https://goobjoog.com/2020/09/29/buurane-waa-ce...,Buurane “Waa Ceyb In Loo Gacan Qaadaa Garsoora...,41,ok,
64,https://goobjoog.com/2015/01/12/warbixinta-gan...,Warbixinta Ganacsiga ee Sanadkii 2014 (AKHRISO),39,ok,
66,https://goobjoog.com/2020/06/28/guddoomiye-saa...,Guddoomiye Saacid “Degmada Warta Nabadda Taari...,47,ok,
70,https://goobjoog.com/2020/06/16/ibraahim-geedo...,Ibraahim Geedow “Dhismaha Stadium Muqdisho Wa...,30,ok,
73,https://goobjoog.com/2019/03/28/jubaland-maxaa...,Jubaland-Maxaa Sababay Guuladaradii Kooxda Kaneva,33,ok,
79,https://goobjoog.com/2022/02/08/shirkadda-nike...,Shirkadda Nike Oo Joojisay Wadashaqeyntii Ay L...,2,ok,
80,https://goobjoog.com/2019/03/21/garsoorayaal-s...,Garsoorayaal Soomaaliyeed Oo Kasoo Muuqday Is ...,0,headline_only_no_body,
81,https://goobjoog.com/2022/02/09/garoonka-camp-...,"Garoonka Camp Nou Oo Magaca Laga Beddelayo, Sh...",2,ok,
104,https://goobjoog.com/2020/06/09/shacabka-muqdi...,Shacabka Muqdishu Ayaa Aragti Duwan Ka Bixiyay...,49,ok,
109,https://goobjoog.com/2022/02/09/dhacdadii-uu-s...,Dhacdadii uu Sadio Mane kula kulmay Isbitaalki...,2,ok,
110,https://goobjoog.com/2020/06/21/115624-2/,Daafaca Xulka Soomaaliya Maxamuud Cali Maxamuu...,43,ok,
115,https://goobjoog.com/2020/08/04/qaar-ka-mid-sh...,Qaar Ka Mid Shacabka Muqdisho Oo Soo Dhaweeyay...,42,ok,
131,https://goobjoog.com/2020/09/30/dhakab-gurey-g...,Dhakab Gurey “Guul Ayay Noo Tahay Helitaanka G...,0,headline_only_no_body,
140,https://goobjoog.com/2020/06/18/ibraahim-geedo...,Ibraahim Geedow “ Xulka Qaranka Uma Baahan Mac...,14,ok,
141,https://goobjoog.com/2020/12/23/wasiir-najax-r...,Wasiir Najax “Rajadeenu Waa Hanashada Koobka M...,3,ok,
172,https://goobjoog.com/2020/06/04/dacar-madaxda-...,Dacar “ Madaxda Xiriirka Is Badal Ha Ogalaadaan”,26,ok,
188,https://goobjoog.com/2022/10/15/madaxweyne-xas...,Madaxweyne Xasan oo Hambalyo u Diray Xulka Qar...,0,headline_only_no_body,
190,https://goobjoog.com/2020/12/17/madaxweyne-axm...,Madaxweyne Axmed Madoobe”Ciyaaraha Maamul Gobo...,3,ok,

,url,headline,body_word_count,status,body
0,https://goobjoog.com/2020/12/31/yaa-guulaysan-...,Yaa Guulaysan Doono Gobolka Banaadir Iyo Galmu...,224,ok,Kooxaha Kubbadda Cagta Gobolka Banaadir iyo Ga...
1,https://goobjoog.com/2020/10/25/xildhibaan-sha...,Xildhibaan Shaacir “Guul Ayaan U Rajaynaayaa W...,179,ok,Xildhibaan Cabdullahi Maxamed Aadan (Shaacir) ...
2,https://goobjoog.com/2024/01/21/akhriso-tartan...,Akhriso: Tartanka Dowlad Goboleedyada oo Dib u...,319,ok,Garoonka Kubadda Cagta ee Stadium Muqdisho wax...
3,https://goobjoog.com/2020/07/11/maxamuud-maxam...,Maxamuud Maxamed “Waxaan Diyaar U Nahay Horoma...,199,ok,Maamulka Ciyaaraha Degmada Diinsoor ayaa tarta...
4,https://goobjoog.com/2019/06/10/wax-badan-ka-o...,Wax Badan Ka Ogaw Kulanka Horseed VS Muqdisho ...,320,ok,Kooxda Ciidanka xooda dalka ee Horseed ayaa wa...
5,https://goobjoog.com/2020/06/16/ibraahim-geedo...,Ibraahim Geedow “Xiriirka Kubbbadda CagtaS Soo...,57,ok,Ibraahim Geedoow Cawaale oo ah qoraa iyo falan...
6,https://goobjoog.com/2020/08/29/daadir-amiin-w...,Daadir Amiin “Waan Ku Faraxsanahay Hanashada H...,110,ok,Kooxda Geeska Afrika ayaa ku guulaystay horyaa...
7,https://goobjoog.com/2019/03/28/hordhaca-horya...,Hordhaca Horyaalka Somaaliya-Yaa Guulo Badan K...,523,ok,Kooxda ciidan booliska Soomaaliyeed ee Heegan ...
8,https://goobjoog.com/2019/11/21/daaru-tarbiya-...,Daaru Tarbiya Oo Ku Guulaystay Tartanka Iskuulada,225,ok,Waxaa lasoo gaba-gabeeyay koobkii kubbadda cag...
9,https://goobjoog.com/2019/09/28/guddoomiye-cab...,Guddoomiye Cabdiqani Saciid “Xulka Dhallinyara...,337,ok,Xiriirka kubbadda cagta Bariga iyo Bartamaha A...